### ISSUE TITLE
Projects - Create the Work Package Dependencies Component

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#157]
Create the view-only component for displaying work package dependencies. This should cleanly and readably display each element nicely spaced within a card component. Clicking on any one of the elements should navigate the user to the page corresponding with the element ([See here for an example](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/78c2714e109ab37814f3facaa04b7b0c3d163a6f/src/components/work-package-summary/work-package-summary.tsx#L36)). Refer to the design sketch v4 snippet below for inspiration and context.

----

Here's a quick outline of steps for this issue. Check them off and / or suggest edits to them as you make progress on the issue. Existing dummy components may be useful to consult for guidance ([see here](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/src/components/change-request-details/change-request-details.tsx), and [here](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/issues/91)).

- [ ] Create the component folder in `/src/components/`
- [ ] Create the test file, component file, and ccs module in the component folder
- [ ] Add basic TS functional component boilerplate to component file
- [ ] Add basic test suite `describe()` to test file
- [ ] Add the component to the app-authenticated component (so you can see the component when starting the app in development)
- [ ] Configure component props to take in the proper work package dependencies array
- [ ] Display all desired component props in the tsx
- [ ] Add DOM element division to begin arranging / styling data elements
- [ ] Add styling to CSS module file
- [ ] Attach CSS styling to proper sections / DOM elements in tsx
- [ ] Get the component to an aesthetically pleasing state that resembles the design sketch snippet below
- [ ] Open a PR with a screenshot of the component to get review and feedback
- [ ] Iterate and make changes based on feedback
- [ ] Once approved for merging, attach a screenshot of the finished component to this issue

---
Design Sketch v4 Snippet: See the card titled "Dependencies"
<img width="809" alt="Screen Shot 2021-04-21 at 9 43 33 AM" src="https://user-images.githubusercontent.com/51571627/115590627-0a79bd80-a286-11eb-9104-f1ad55bffa85.png">

**Comment by lpfahler16** [comment]
<img width="842" alt="Screen Shot 2021-04-29 at 2 13 58 PM" src="https://user-images.githubusercontent.com/46872232/116763278-3e25b780-a9eb-11eb-91c1-2f6c16210776.png">
