### ISSUE TITLE
Projects - Create Single Project Container

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#163]
Container components execute API calls and pass data down to child components. In order to assemble a component for a single project and provide it with the data it needs, we need a work packages container component.

- [x] Create a basic react component folder structure in the `src/containers` folder. (the folder and the 3 files it should contain)
  - [x] Create the test file, component file, and ccs module file in the component folder
  - [x] Add basic TS functional component boilerplate to component file
  - [x] Add basic test suite describe() to test file
  - [x] Add the component to the main app component (so you can see the component when starting the app in development)
- [x] Assemble the children components in the container component
  - [x] Add the Project Details Component as a child component
  - [x] Add the Work Packages Summary List Component
- [x] Wire up a use effect hook to fetch data from the proper API endpoint
- [x] Store the work package locally and pass it down to the children components
- [ ] Ensure you attach a screenshot when opening a PR
  - [x] Get the component to an aesthetically pleasing state that resembles the design sketch snippet below
    - Skip the breadcrumbs at the top of the page
    - Skip the actions dropdown menu in the top right corner
    - Skip the Gantt chart card that's in the middle between the details component and the summary list component
  - [x] Open a PR with a screenshot of the component to get review and feedback
  - [ ] Iterate and make changes based on feedback
  - [ ] Once approved for merging, attach a screenshot of the finished component to this issue

---
Design Sketch v4 Snippet:
<img width="760" alt="Screen Shot 2021-02-07 at 12 03 53 AM" src="https://user-images.githubusercontent.com/51571627/107140595-f86bbe00-68d7-11eb-9389-641cf012276b.png">

**Comment by lpfahler16** [comment]
![](https://user-images.githubusercontent.com/46872232/119759231-e35e6f00-be75-11eb-9420-1103a9f1226c.png)
