### ISSUE TITLE
Research - User Authentication

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#17]
In v1 of the app, Google handles all sign-in and restricts users to the Northeastern Google Suite domain. In v2, we will need to handle user authentication ourselves. Research various options to help streamline this workflow.

Some options to consider:
- [Google OAuth](https://developers.google.com/identity/sign-in/web/sign-in)
- [react-google-login](https://www.npmjs.com/package/react-google-login)
- [~~sign-in with apple~~](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple)
- [Auth0](https://auth0.com/blog/complete-guide-to-react-user-authentication/)
- [from scratch](https://www.digitalocean.com/community/tutorials/how-to-add-login-authentication-to-react-applications)
- [Okta](https://developer.okta.com/blog/2019/03/06/simple-user-authentication-in-react)
- [JSON Web Tokens (aka JWT)](https://www.alibabacloud.com/blog/how-to-implement-authentication-in-reactjs-using-jwt_595820)

Consider the relative difficulty of implementing each workflow with our React application, the features provided, the costs, and the potential impact on user experience.

**Comment by eshwaribhide** [comment]
I think the 1st and 2nd are basically the same in our context; the official description for react-google-login is "A Google oAUth Sign-in / Log-in Component for React". So I'll consolidate those two. I kind of feel like this is the best option, though I'll look into the others.

It's free to use and is made for React, and thereby is not difficult to work with our app; the documentation on the website shows the code you could pretty much just copy paste to get it working. You'll "get" the typical "Sign in with Google" button and also a "Logout of Google" button. You can also create custom-looking buttons. It's possible to allow the user to stay signed in. 

It's also easy to obtain information on the logged in users. The onSuccess callback, if the user is not offline, will give you a GoogleUser object, which basically has a [method](https://developers.google.com/identity/sign-in/web/reference#googleusergetbasicprofile) called `getBasicProfile()` which will return you important user information like the user's name and email (other stuff too)

**Comment by eshwaribhide** [comment]
I'm not sure about Sign in with Apple, what if some people don't have an Apple ID (it's possible)? I feel like everyone kind of has a Google Account. If we really wanted to look into it, I think there's [react-apple-login](https://www.npmjs.com/package/react-apple-login), similar to react-google-login.

**Comment by eshwaribhide** [comment]
Tbh I could look into the other options if you'd like, but I feel like react-google-login sounds easy and like a good option to use.

**Comment by jamescd18** [comment]
Okay, that eliminates Sign In with Apple. If you've got the time, briefly take a look at the differences between the others.

**Comment by eshwaribhide** [comment]
Upon investigating the other options, I think they all (except Auth0) seem to require much more work than something like react-google-login. First, I also don't think we should really be doing this from scratch if there are other established options, and it also just seemed like a lot of work. 

In terms of Auth0, the extra thing is that you have to create an account and then from the Auth0 Dashboard Application Settings, have to configure Callback URLs, Logout URLs, and Allowed Web Origins by just adding the appropriate URLs. Then you have to install the Auth0 React SDK (just through npm) and after that setting up login and logout is pretty straightforward, you can pretty much just copy paste what they have done [here](https://auth0.com/docs/quickstart/spa/react). I would say that what differentiates Auth0 from Google sign in is that it allows you to add authentication with multiple sources, so not just sign in with Google but also with LinkedIn or GitHub for example. Not sure if we really care though, as I think the people using our app will all have Google accounts. 

Okta and JSON Web tokens just seemed like they would take a lot more time to set up. They both require the use of React Router, which I know we are going to be using but still. Also JSON Web Tokens seemed to require a bunch more dependencies.

**Comment by eshwaribhide** [comment]
So I'd say we can decide between react-google-login and Auth0.

**Comment by jamescd18** [comment]
Thank you so much for digging into it! That's a really good analysis. User authentication isn't a super high priority for us, so it's likely that we won't implement it until later. For now, let's go ahead and tentatively say we're going to use react-google-login, and we'll double check before we start diving into it. Feel free to open a PR for the readme updates.
