### ISSUE TITLE
Research - Rendering Charts in React

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#20]
Research various options to cut development time with rendering charts in the front-end using a package. The package must include support for Gantt charts. Ideally, the package should offer some decent level of features, but nothing overly complex.

A potentially primary option would be [react-google-charts](https://react-google-charts.com), but there definitely are alternatives to explore.

**Comment by eshwaribhide** [comment]
I think that react-google-charts seems like the best option...it seems pretty easy to use and set up and has Gantt chart support. I tried exploring some alternatives. One was [Recharts](https://recharts.org/en-US/), which seems like a good and popular option, but I don't think it supports Gantt charts. There is another library called [Victory](https://formidable.com/open-source/victory/), but it also doesn't seem to directly support Gantt charts directly and might be more complex than we need.

I found an open source option called [react-gantt](https://github.com/clayrisser/react-gantt), but this is made specifically for Gantt charts, so is not as flexible if we need to also render other types of charts or something. 

There is also Airbnb's [visx](https://airbnb.io/visx/) ([Github repo](https://github.com/airbnb/visx)). In this article, [one of the examples they made with visx was a Gantt chart](https://medium.com/airbnb-engineering/introducing-visx-from-airbnb-fd6155ac4658#0062:~:text=)%3A%20Dependency%2Dinclusive%20gantt%20chart%20for). It's interesting, one [article](https://livecodestream.dev/post/7-react-chart-libraries-for-your-web-projects/) that literally is titled "7 React Chart Libraries For Your Web Projects" said visx is "well equipped to generate complex charts", though Airbnb makes it explicit that they don't want to call it a charting library, saying, "As you start using visualization primitives, you’ll end up building your own charting library that’s optimized for your use case." But anyways, that statement really shows that it has a lot more complexity than necessary, and it's a more low level thing, and there don't really seem to be examples online of building Gantt charts with visx (and no direct, obvious support).

**Comment by jamescd18** [comment]
That's super interesting to hear! I'm glad you were able to both explore alternative options and bring up a very interesting one I'd never heard of before. I think our plan moving forward will be to use react-google-charts, and then if our charting needs become more complex, we can consider visx. Feel free to open a PR linked to this issue to mark it as researched and decided.
