### ISSUE TITLE
Projects - Create Table Filter Component

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#202]
**Background:**
In order to allow users to filter projects, we need a companion filter configuration component for the projects table. This filter configuration component will need to support various different input fields for filtering the various different attributes of a project.

---

**Behavior:**
Specifications and behaviors are as follows. They may be complex to implement, so don't be afraid to do a little Googling, a little Youtube searching, and of course, ask for help from @kevinyu328 or @jamescd18.
- There should be a filter input box for the car number (must only accept numerical values, no decimal places)
- There should be a filter option dropdown for project status (active, completed, inactive)
- There should be a filter option dropdown for project lead, and one for project manager
- All filters should have a default no selection option

---

**Steps:**
- [x] Create the basic component
  - [x] Create a basic react component folder structure in the `src/components` folder
  - [x] Create the test file, component file, and ccs module file in the component folder
  - [x] Add basic TS functional component boilerplate to the component `.tsx` file
  - [x] Add basic test suite `describe()` with at least one `it()` test case to the test file
  - [x] Add the component to the `projects-table` container (so you can see the component when starting the app in development)
- [x] Add the desired functionality
  - [x] Search through [react-bootstrap](http://react-bootstrap.github.io) to find the correct template component code to use
  - [x] Add the input fields to the component
  - [x] Add label text for each input field
  - [x] Configure the logic specified in the behavior section
  - [x] Add `useState()` local variables to store state variables that need to change
- [x] Apply styling
  - [x] Check that the label text is styled like label text
  - [x] Check that the layout of the input fields roughly matches the behavior and the sketch (sketch may be inaccurate, treat the behavior description as the more correct one, and don't be afraid to get feedback and iterate on the design)
- [x] Create test cases
  - [x] Test that the label text is visible
  - [x] Test that the input fields are there
  - [x] Test that the behavior logic is working properly
- [x] Open a PR with a screenshot of the component to get review and feedback
  - [x] Ensure you attach a screenshot when opening a PR
  - [x] Ensure you follow the [instructions in the contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md#creating-a-pull-request)
  - [x] Iterate and make changes based on feedback
  - [x] Once approved for merging, attach a screenshot of the finished component to this issue

---

**Sketch:**
The projects filter section is highlighted with a red box around it. Ideally [flexbox](https://getbootstrap.com/docs/4.0/utilities/flex/) would be used to ensure items within the component are responsive.
<img width="745" alt="Screen Shot 2021-05-12 at 9 04 40 PM" src="https://user-images.githubusercontent.com/51571627/118075842-b97d5680-b365-11eb-901a-9132b8864c9a.png">

**Comment by Ari-S-123** [comment]
Screenshot of the finished component.

![Screenshot (1042)](https://user-images.githubusercontent.com/80832201/142338261-023470a5-8a4e-4978-9bea-4e95f2e62f93.png)
