### ISSUE TITLE
Research - GitHub Actions for CI

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#22]
Continuous Integration is an important part of the software development workflow to increase speed of development and confidence in the codebase. 

Research [GitHub Actions](https://github.com/features/actions) as the primary option for incorporating CI into the application development workflow. You may also want to consider alternatives like [Travis CI](https://www.travis-ci.com), [Circle CI](https://circleci.com), and [Jenkins](https://www.jenkins.io). Consider things like ease of use, features, integration with testing ([see potentials here](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2#project-setup-checklist)), and pricing.

Bonus points for potential configurations like label-based checks and more.

**Comment by eshwaribhide** [comment]
Imagine us actually using Jenkins 😂
