### ISSUE TITLE
Research - Database Hosting Platform

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#23]
Explore PostgreSQL hosting providers in an effort to understand which cloud-based fully-managed database hosting provider would be best. Also see #4. Options include: (feel free to trim the list before digging too deep)

- [Digital Ocean](https://www.digitalocean.com/products/managed-databases-postgresql/)
- [Azure PostgreSQL](https://azure.microsoft.com/en-us/services/postgresql/)
- [AWS RDS for PostgreSQL](https://aws.amazon.com/rds/postgresql/)
- [Google](https://cloud.google.com/sql/docs/postgres)
- [ScaleGrid](https://scalegrid.io/pricing.html?db=POSTGRESQL&cloud=cloud_oci&replica=deployment_standalone&instance=Medium#section_pricing_dedicated)
- [Heroku PostgreSQL](https://www.heroku.com/postgres)
- [ElephantSQL](https://www.elephantsql.com)

Pricing is likely the most important axis of comparison. From rough napkin math, we anticipate having <1GB of data and a relatively small CPU load, but this could change. The 1-3 lowest price tiers are likely of most interest, and it would be beneficial to compare and see how features / performance scales with price for each provider. If prompted, bias towards hosting on the east coast, but do consider the price differences.

**Comment by eshwaribhide** [comment]
Provider |   Price  |  Storage  | vCPU
 -------  | -------- | -------- | --------
Digital Ocean | $15/mo | 10 GB | 1
Azure PostgreSQL | $25.32/mo | 5 GB | 1   
Azure PostgreSQL | $25.82/mo | 10 GB | 1
AWS RDS for PostgreSQL | $13.71/mo | 5 GB | 2*
AWS RDS for PostgreSQL | $106/yr + $0.57/mo | 5 GB | 2*
AWS RDS for PostgreSQL | $14.29/mo | 10 GB | 2*
AWS RDS for PostgreSQL | $106/yr + $1.15/mo | 10 GB | 2*
Google                 | $51.01/mo          | ~10.7 GB | 1
ScaleGrid              | $90/mo             | 60 GB    | 1
ElephantSQL	       | $10/mo             | 1 GB     | Doesn't say...so I assume 1


*I don't see an option for one with 1 vcpu.

Digital Ocean & Azure don't appear to have upfront pricing.

Let's forget about Google...that is a ridiculously expensive price and also they don't even host on the East Coast (closest thing is Iowa).

**Comment by jamescd18** [comment]
[Connecting to Heroku Postgres Databases from Outside of Heroku](https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku)

The important distinction about ScaleGrid is that it allows you to choose the underlying cloud service. You can choose AWS, Azure, GCP, or others with ScaleGrid.

**Comment by eshwaribhide** [comment]
For now, let's say that our contenders are Digital Ocean, Azure, AWS, and ElephantSQL. 

I'm going to say that Azure seems a bit pricier, so let's forget about it for now. Same with DigitalOcean, whose minimum also happens to be 10 GB, which is more than we need (and at $15/mo for 10 GB, it's more than AWS at $14.29/mo for 10 GB). So we can decide between AWS and Elephant

> [Connecting to Heroku Postgres Databases from Outside of Heroku](https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku)
> 
> The important distinction about ScaleGrid is that it allows you to choose the underlying cloud service. You can choose AWS, Azure, GCP, or others with ScaleGrid.

But is it really worth $90 a month?

**Comment by eshwaribhide** [comment]
> [Connecting to Heroku Postgres Databases from Outside of Heroku](https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku)
> 
> The important distinction about ScaleGrid is that it allows you to choose the underlying cloud service. You can choose AWS, Azure, GCP, or others with ScaleGrid.

Is it really worth $90 a month though?

**Comment by jamescd18** [comment]
Looks great! I love the fantastic notes and wonderful analysis. Let's go ahead and mark this as AWS RDS and see where it takes us.
