### ISSUE TITLE
General - Setting Up Path Mapping 

### ISSUE THREAD

**Issue by VerySeriousHireableAccount** [Northeastern-Electric-Racing/PM-Dashboard-v2#314]
Setting up [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) in ts.config file to shorten import statements. Multiple paths can be created for clean importation of hardcoded test data, shared components (pipes, error pages,...) or services,etc

**Comment by jamescd18** [comment]
Won't fix. This has been explored and determined to be a little more difficult than is worth it.
