### ISSUE TITLE
Docs - Better Documentation for Database Migration and Seeding

### ISSUE THREAD

**Issue by acd124** [Northeastern-Electric-Racing/PM-Dashboard-v2#340]
## Background:
The `database-setup` branch was created in order to implement the messy and sweeping changes it took to properly configure and set up the back-end to query data from the database. Having the application connected to a database in development entails additional knowledge around using the database that all developers must learn.

## Description:
Prior to merging the `database-setup` branch into `main`, we need to ensure that all team members present and future are or will be able to run the application in development. Ensuring others are able to run the application with the newly required database means properly documenting the steps required to fully set up the database and operate it using Prisma. Document the database migration and seeding as part of the database setup in the contributor docs. See the `prisma:migrate`, `prisma:seed`, and all other Prisma-related npm scripts.

**Comment by jinhyunh** [comment]
https://docs.google.com/document/d/1y1hMYbGLkjrgl3DwfgE6dtVjzpqiDjN-zltIpPz2VEU/edit?usp=sharing
