### ISSUE TITLE
General - Perform production database migration & setup

### ISSUE THREAD

**Issue by KincentLan** [Northeastern-Electric-Racing/PM-Dashboard-v2#343]
## Description

Perform various tasks to prepare the production database for testing.

## Prerequisites

The create and implement change request epics must be completed first
- [x] #374
- [x] #397  

## Proposed solution

- [ ] Export all data from the production database
- [ ] Run the Prisma database migrations on the production database
- [ ] Modify exported data into import-ready script by removing table modification commands and re-ordering insert commands to ensure proper order of dependent tables
- [ ] Run data import script to re-load the database
- [ ] Configure the database user
- [ ] Document the process

## Other Notes

Following the principle of least privilege, we want to make sure that normal application users cannot modify tables that they are not normally supposed to. Normal application users should only be able to read and create, not delete or modify.

we want to load some data into the production database so we can test the production environment to make sure everything is running smoothly.

Reach out to @jamescd18 for pair-programming on this issue (as you need proper privileges to modify the production database).

**Comment by jinhyunh** [comment]
https://docs.google.com/document/d/1y1hMYbGLkjrgl3DwfgE6dtVjzpqiDjN-zltIpPz2VEU/edit?usp=sharing
