### ISSUE TITLE
General - Set up users and permissions on the production database

### ISSUE THREAD

**Issue by KincentLan** [Northeastern-Electric-Racing/PM-Dashboard-v2#345]
Following the principle of least privilege, we want to make sure that normal application users cannot modify tables that they are not normally supposed to. Normal application users should only be able to read and create, not delete or modify.

Reach out to @jamescd18 for pair-programming on this issue (as you need proper privileges to modify the production database).

**Comment by jamescd18** [comment]
Now covered by #343
