### ISSUE TITLE
General - Main Branch Actions Fail Due to Unrecognized Package

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#356]
The GitHub Actions (tests and linting) fail on the main branch because `npm install` fails. The `npm install` command fails because it does not recognize one of the package names. This package is not listed in the `package.json` file, which is what leads me to believe it is an issue with the `package-lock.json` file, but this is just a hunch.

**Comment by KincentLan** [comment]
Mysteriously worked again.
