### ISSUE TITLE
Database - Create an ERD

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#37]
In order to properly set up an SQL database for use with our application, we need to plan out what data we will store and how the data will be related. Use the current [database spreadsheet](https://docs.google.com/spreadsheets/d/1rHjZjk8FvP9gmRe2K9uRl0dxCtA2BZr_tcvux8yk7Eo/edit#gid=1128732883) and the below screenshot for inspiration when building out the ERD in [this diagrams.net document](https://app.diagrams.net/#G1B60hi-NXQ0ypNe-VTRqDMJbN6YwDhC4F). This will be an interactive process, and starting earlier is bound to make things easier for us.
<img width="1121" alt="Screen Shot 2021-01-28 at 9 42 25 PM" src="https://user-images.githubusercontent.com/51571627/106236438-b6dd6380-61b1-11eb-882e-359b98aba5f7.png">

**Comment by eshwaribhide** [comment]
![PM-System-Database](https://user-images.githubusercontent.com/52673645/106519409-16788f00-6490-11eb-8606-047f562cb71f.jpg)

**Comment by eshwaribhide** [comment]
![PM-System-Database](https://user-images.githubusercontent.com/52673645/106519480-3314c700-6490-11eb-9e89-c5029222309f.jpg)

Current version of ERD
