### ISSUE TITLE
Change Requests - Reviewing Change Requests

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v2#375]
## Background:
Change requests are submitted by project managers or project leads to change specific details of projects or work packages. Reviewing change requests give the e-board and project leads the ability to authorize changes and keep track of progress towards the overall goal.

## Tickets:
- [x] #354
- [x] #431 
- [x] #428
- [x] #372 
- [x] #371

**Comment by jamescd18** [comment]
Deployed to prod!
