### ISSUE TITLE
General - Remove Dummy Data

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#382]
## Background:
The dummy data file located in the `utils` package previously was used as static data available to all of the back-end endpoint files. The back-end would return this static dummy data as opposed to grabbing data from the database because at that time the database did not exist and wasn't set up.

## Description:
Following the setup and implementation of the database connection in the back-end as part of #381 for the `database-setup` branch, we now need to entirely remove the dummy data file from the project. Once the back-end no longer uses anything from the dummy data file, it should no longer be need, and thus leaving it would only bloat the `utils` package. Simply put, cleanly remove the dummy data file and ensure the app still works properly. Merge into `database-setup` branch only.

**Comment by acd124** [comment]
Already completed as per commit f9ec440c98a9fe11dac91752e34e6bb261836787
