### ISSUE TITLE
General - Address Technical Debt & Bugs for MVP Soft Launch

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v2#398]
### Background

Various shortcuts have been taken in order to create components quickly so that dependent work is not blocked. In some cases, placeholder text has been used and in other cases, best practices have not been followed. This epic is to address these shortcuts so that we can launch the application with a cleaner codebase.

### Tickets

 - [x] #416 
 - [x] #415
 - [x] #400
 - [x] #429
 - [x] #391
 - [x] #419
 - [x] #426
 - [x] #399

**Comment by jamescd18** [comment]
All tickets have been completed and merged to main! We will create a new and separate epic to bundle up other required tickets for MVP medium launch
