### ISSUE TITLE
General - Remove Up-Down Arrow Button in Text Boxes

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/PM-Dashboard-v2#403]
## Description

Remove arrow button in the top right corner of every text box in the application (on project, work package, and change request pages). This is a low-priority bug that isn't impacting usage or functionality.

## Steps to Reproduce

1. Open the Application
2. Navigate to a page with a text box (e.g. single project page)
3. See the button

## Proposed Solution

These arrows are unintentional and have no functionality, so they would be better removed. "I suspect it is part of a larger scroll bar thingy that may or may not be avoided by looking into our CSS." - James

You might find inspiration from #418 / #498 because that ticket / PR does some CSS magic. Experimenting with CSS via the developer console styles / computed layout is also likely to be very important for this ticket. Also Googling around to understand CSS.

- [x] Research via Google to determine if this is something other people experience
- [x] Experiment and learn CSS to figure out what might be able to get rid of it without significantly changing the UI
- [x] Open a Pull Request (PR) with a screenshot of the new UI
- [ ] Review and iterate PR

## Screenshots (as needed)

<img width="14" alt="button" src="https://user-images.githubusercontent.com/29521172/147521019-22315c77-adfc-4935-b632-b2aeceab1fd5.png">

**Comment by a-geng** [comment]
<img width="665" alt="Screen Shot 2022-03-01 at 6 41 30 PM" src="https://user-images.githubusercontent.com/32208974/156269838-aff5eb88-fc76-4216-8a6e-d39e11f4e71c.png">
The buttons appear on Windows but not MacOS
