### ISSUE TITLE
Change Requests - Formatting Inconsistencies in Detail Blocks

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/PM-Dashboard-v2#405]
### Description 

CHANGE SO THAT THE TICKET IS FOR FIXING RESPONSIVE LAYOUTS ON ALL CHANGE REQUEST TYPES
The change request detail section for the NEW_FUNCTION change requests needs to be reformatted so that they match the format of change requests of type DESIGN_ISSUE and OTHER.

### Observed Behavior

The NEW_FUNCTION change requests have a different format from the change requests for DESIGN_ISSUE and OTHER. See screenshot below for comparison of the two formats.

### Desired Changes

We want the details section of NEW_FUNCTION change requests to match the format of the DESIGN_ISSUE and OTHER change requests. See the screenshots for the current inconsistent format and desired/normal format.

### Proposed Solution
- [ ] Look through the React component causing this issue and how it is being called/used in the change request details component to figure out why this bug is occurring 
- [ ] Fix bug :)

### Screenshots

<img src="https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/files/8054570/inconsistent.pdf">
<img src="https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/files/8054571/normal.pdf">

**Comment by jamescd18** [comment]
fixed by other ticket #661 #704
