### ISSUE TITLE
General - Logout Button Not Working

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/PM-Dashboard-v2#406]
### Browser(s)

Chrome

### Platform(s)

Desktop

### Version(s)

other (specify below)

### Observed Behavior

When the logout white space around the logout button is clicked, nothing happens. The space around the "Logout" label does not trigger the button and log the user out.

### Expected Behavior

The logout button should log you out of the application and take you back to the login screen when clicked.

### Steps to Reproduce

1. Login to the application
2. Navigate to the Logout Button
3. Try to click the whitespace around the logout button

### Proposed Solution

Adjust the white space so that the click target covers more of the whole area, so that users are able to logout by clicking anywhere on the logout button. 

### Screenshots (as needed)

Menu item target area. Lots of this area is clickable but won't trigger the log out function.
<img width="227" alt="Screen Shot 2022-02-14 at 1 22 55 AM" src="https://user-images.githubusercontent.com/51571627/153811520-5060842a-70e6-4cbb-b13f-2dde38926c5b.png">

When the mouse hovers on the text itself the color changes and this text is the area that when clicked actually triggers the log out function.
<img width="234" alt="Screen Shot 2022-02-14 at 1 23 10 AM" src="https://user-images.githubusercontent.com/51571627/153811658-7ab514a6-caa8-4123-8c46-1b37d96f9602.png">

Video screen recording
https://user-images.githubusercontent.com/51571627/153811441-16ab1343-2b2a-4d80-b3e6-244f824f6628.mov

**Comment by jamescd18** [comment]
The logout button works perfectly for me on macOS Big Sur version 11.0.1 with Safari version 14.0.1

Let's get some more data points and see whether or not this works for others.

**Comment by jamescd18** [comment]
It looks like this could be caused by the text of the button triggering the button, but the space around the text not triggering the button. If that is the case, then we likely need to adjust it so that the click target covers more of the whole area
