### ISSUE TITLE
Auth - Add Loading Spinner to Login Page

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#452]
## Description

 Add a loading indicator on the page right after the user selects their northeastern email account in the popup window

## Background 

It's a little annoying to sit there on the login page while you wait for the authentication server to respond before it will move you over to the actual application, so as a user, it would be much more informative to see evidence of loading when waiting on the login. Currently, it redirects the user back to the login page where it sits for a good 2-3 seconds before finally letting the user into the application. 

## User Story

As a project manager, I want to see if the dashboard is loading after login, so that I know that the dashboard is simply loading rather than freezing.

## Proposed Solution
- [x] Display a loading indicator on the page as soon as the user selects their account in the popup window

**Comment by acd124** [comment]
I think that the page refieren would be a cleaner solution, since then there is no ambiguity with not seeing the pop up or when it's actually gone through.

**Comment by jamescd18** [comment]
When I visit prod on my iPad, it does redirect instead of popup for the login window, and after selecting the account, it pops me back over to the login page where it waits a bit longer before letting me into the app, so I think a loading spinner is still a good thing to add eventually.
