### ISSUE TITLE
Change Requests - Loading same page twice has page scrolled down

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/PM-Dashboard-v2#471]
## Description

Fix bug where after clicking into a page, going back to the previous page, and re-entering the same page that you entered, the page will load from the bottom. 
This bug is reproducible when going 
- [ ] specific project page -> specific work package page
- [ ] specific project page -> specific change request page
- [ ] specific work package page -> specific change request page
- [ ] specific change request page -> specific project page
- [ ] specific change request page -> specific work package page
- [ ] change request page -> specific change request page

In this context, `specific` means a page with an ID attached to it such as Change Request 26, Project 1.12.0, or Work Package 1.23.0.
The bug does not occur when going from the project page -> specific project page.

## Browser(s)

Firefox, Chrome

## Platform(s)

Desktop

## Version(s)

main

## Observed Behavior

When you link to a change request detail page, sometimes the page loads already scrolled down to the bottom of the page if you had visited that page already.

## Proposed Solution

- [ ] Every time you load a change request detail page, your browser should start you at the top of the page.
- [ ] Check to see if the bug exists elsewhere by clicking on links on pages, going back, and re-clicking on the same link.

## Steps to Reproduce

1. Go to any work package or project detail page that has a linked change request.
2. Click on the link to navigate to the change request detail page.
3. Go back to the previous page you were just on (will either be the work package or project detail page)
4. Click on the link to that same change request detail page.

## Screenshots (as needed)

This is what the screen loads with this bug where the page is already scrolled to the bottom:
![onload-cr-page-from-cr2-link](https://user-images.githubusercontent.com/48561685/150464227-6e2fa5ca-6607-463a-be60-50f462cc3dda.png)

**Comment by jinhyunh** [comment]
Steps to Reproduce Demo
1. Navigate to Projects >> Impact Attentuator >> Bodywork Concept of Design >> [#2] Increased duration from 3 weeks to 7 weeks.
2. Exit back to work package page
3. Re-click on [#2] Increased duration from 3 weeks to 7 weeks.

When tested, sometimes it opens the page at the bottom and other times it does not.

**Comment by jamescd18** [comment]
Steps for solving this ticket
- Step 1: determine if this is actually consistently reproducible or not
- Step 2: determine if this is experienced by other people building react apps in general
- Step 3: determine if it is worth our time to dig deeper

**Comment by jonathan-chen10** [comment]
The program is probably keeping the scroll state of the previous page when it re-loads the next page from cache. 

### Actions Taken
Shelve this issue for now as we focus on higher-priority issues.
