### ISSUE TITLE
Change Requests - "Who Is Required for Design Review?" section may be unnecessary

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/PM-Dashboard-v2#484]
### Desired Changes

No changes are currently requested. Rather, it would help to have an explanation for why this section is needed and what the input for this section is used for in the change request details page. As noted in #384, I could not figure out which column in the data tables this section referred to. Consequently, I feel this section may be unnecessary, but I may be wrong and not fully understand our design.

**Comment by AEGIPPP** [comment]
Currently handled by PMO via Slack communication. PMO sends out calendar invites to all relevant parties based on info living in our heads (aka who's been working on the project, who is required for review, who might find the review interesting, etc.).

Not necessary in terms of data collection and our operations. Will be useful in the event it's able to auto send out invites.

**Comment by jamescd18** [comment]
Removing for now since we do not store the data in the database. Der Chi's note is correct though, the future intention is to build an integration that schedules a Zoom meeting, creates a Google doc from the template, and sends out invites to the users. Future thing though.
