### ISSUE TITLE
Change Requests - "Type" input has incorrect option 

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/PM-Dashboard-v2#485]
### Description

There needs to be some fixes for the options avalable for the type of change request.

### Browser(s)

Firefox

### Platform(s)

Desktop

### Version(s)

main

### Observed Behavior

In the dropdown for selecting the type of a change request "Initiation" is an option. However, there is no "Initiation" type change request. "Activation" change requests, however, are missing from the dropdown.

### Proposed Solution
"Activation" should be an option in the dropdown and "Initiation" should not.

Ensure that the values in the dropdown are generated from `Object.values(ENUM)` where `ENUM` is the proper enum for the values in the dropdown.

### Steps to Reproduce

1. Go to new change request form
2. Select dropdown for the "Type" input

![new-cr-initiation-type](https://user-images.githubusercontent.com/48561685/150611889-1f06fcb6-0a9f-4cbc-8eca-154f3ac48854.png)

**Comment by usayd-sheikh** [comment]
#570 Merged PR
