### ISSUE TITLE
General - Create Prettier Script

### ISSUE THREAD

**Issue by acd124** [Northeastern-Electric-Racing/PM-Dashboard-v2#530]
### Description

Create a script to run prettier on all files, similar to the `lint` script used to run eslint on all files at once.

### Background

We use prettier to automatically format files so the code is easier to read and consistent. We recommend that everyone uses format on save to make sure that every file they work on is properly formatted, but that isn't and hasn't always been done, so it is useful to be able to check and/or fix all the formatting issues.

### Proposed Solution

An npm script very similar to the `lint` script the check all relevant files. Make sure that things like the docs (text files), and ignored files aren't accidentally included in the check. At the very least all `.ts` and `.tsx` files in the `src` folder should be checked, though there may be other files that warrant being checked.

**Comment by jpwaves** [comment]
I think having two scripts, one to merely check if there are files that violate prettier format, and one that actually goes in to automatically fix them (`--fix` flag) would be useful.
