### ISSUE TITLE
Projects - Create Work Package Endpoint Should Use `buildClientFailureResponse` Not `throw new TypeError()`

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#547]
## Description

Specifying errors on the 4xx level instead of 5xx would allow for project managers to independently troubleshoot any usage errors, omitting unnecessary follow-up with the software team.

## Background

Currently, the implementation of `throw new TypeError()` returns only 500 internal server error responses, which provides minimal feedback to users on what went wrong.  

## Desired Behavior

4xx level errors should be returned.

## Proposed Solution

The `buildClientFailureResponse` function should be implemented instead of `throw new TypeError()`, enabling error messages to be sent back to the front-end and be properly handled. Some reading material [here](https://www.tutorialspoint.com/session_initiation_protocol/sip_client_failure_responses.htm).

**Comment by jpwaves** [comment]
See `/src/backend/functions/project-new.ts` for examples on how to use the pre-built functions for throwing 4xx errors
