### ISSUE TITLE
General - Apply Prettier to all files

### ISSUE THREAD

**Issue by jpwaves** [Northeastern-Electric-Racing/PM-Dashboard-v2#576]
### Desired Changes

Run `npm run prettier:write` and fix any issues that arise from having prettier enforced.

### Prerequisites

- [x] #530

### Acceptance Criteria

- Running `npm run prettier:check` succeeds without any errors
- All functionality is the same -- nothing is broken

### Screenshots (as needed)

List of files that currently show warnings:
![prettierlogs1](https://user-images.githubusercontent.com/48561685/157773907-37cf1878-1468-42d8-a2df-e60e3899da78.png)

**Comment by jamescd18** [comment]
I think we missed it. `.text.tsx` should be called out specifically
