### ISSUE TITLE
General - Create Navbar Component

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v2#59]
Create the navbar component that will be used throughout the site. You can create your own navbar with CSS or use one of the Bootstrap navbars as a starter and edit it to fit our design. Refer to the V3 design sketches for what the navbar should look like. As for colors, the background of the navbar should be red. The specific hex code for the red that should be used is here in [this document](https://docs.google.com/document/d/1bV-TGorNeGbn7BhrwP9_nhSb_qmfs5wxJeJY5AfekDo/edit). There aren't any constraints to the colors of the text, so feel free to try out a couple and take some screenshots or implement different colors/styles in separate files.

**Comment by jamescd18** [comment]
Look and feel should be pretty similar to NER-PM-Dashboard-v1's simple title with red background header. This time we're just left justifying the title and adding user details to the right side.
