### ISSUE TITLE
Projects - Project Details Page Displays Deleted Bullets

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#592]
### Browser(s)

Chrome, Firefox, Safari

### Platform(s)

Desktop, iOS, Android

### Version(s)

main, production

### Observed Behavior

After editing a project to delete certain bullets, those deleted bullets still show up on the project's details page.

### Expected Behavior

Deleted bullets are hidden.

### Steps to Reproduce

1. Edit a project and delete a bullet
2. Reload the project details page

### Screenshots (as needed)

<img width="1613" alt="Screen Shot 2022-03-28 at 12 01 37 AM" src="https://user-images.githubusercontent.com/51571627/160324668-7c51b070-ac0c-4bb8-80de-34e069fecc5e.png">

**Comment by anthonybernardi** [comment]
this is also fixed
