### ISSUE TITLE
Projects - Projects Edit Page Fails With no Project Lead or no Project Manager

### ISSUE THREAD

**Issue by acd124** [Northeastern-Electric-Racing/PM-Dashboard-v2#598]
### Browser(s)

Chrome, Firefox, Safari

### Platform(s)

Desktop, iOS, Android

### Version(s)

main, production

### Observed Behavior

When a project has no project lead or project manager (like when initially created), clicking the edit button breaks the app. The app starts loading then just going to a blank page. The error in the terminal shows: `TypeError: undefined is not an object (evaluating 't.userId')`

### Expected Behavior

The project edit page should display properly when there is no project lead or manager

### Steps to Reproduce

1. Find a project with no project lead or no project manager. (Or just create a new one)
2. Click on the project in the projects table
3. Click the edit button in the top right.
4. Watch the page go blank

**Comment by anthonybernardi** [comment]
this got fixed at some point so we good
