### ISSUE TITLE
General - Create Sidebar Component 

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v2#60]
Create the sidebar component for the website. The plan is to have each icon as an individual component and to have one component that includes all the individual icon components. Refer to the V3 design sketch for how the sidebar should look. @jamescd18 has some Font Awesome icons in mind, so reach out to him for the specifics. The background color of the sidebar is undecided, so feel free to play around with colors to see what you think looks best. You can create separate files to show different styles/colors or take screenshots of some of the different styles/colors you experimented with. [This document ](https://docs.google.com/document/d/1bV-TGorNeGbn7BhrwP9_nhSb_qmfs5wxJeJY5AfekDo/edit) has some of the specific color codes the club uses for branding.

**Comment by jamescd18** [comment]
Here is a sneak peak at design sketch v4. Icons are pulled from font awesome. To be extra specific:

- generic home icon
- bar chart turned on its side
- folder icon
- two arrows pointing opposite directions left and right
- stonks line chart going up to the right
- question mark help icon

![image](https://user-images.githubusercontent.com/51571627/106844560-b6cfde80-665d-11eb-8a11-eb8db511c24f.jpeg)

**Comment by albeartoz** [comment]
To consider:
 - https://www.npmjs.com/package/react-pro-sidebar 
 - https://www.npmjs.com/package/react-sidebar 
 - https://www.npmjs.com/package/react-burger-menu

**Comment by jamescd18** [comment]
Awesome! Just like you said, best not to reinvent the wheel. Looking a little more closely at these three, it seems like either way, it'll require a bit of customization to get it to where we'd like it to be. The first is a lot newer and less popular than the other two, but that shouldn't matter too much. Just pick whichever you think would be best, and style it appropriately to align with the vision outlined in the sketch picture above.

**Comment by jamescd18** [comment]
This is what the new sidebar should look like
<img width="1079" alt="Screen Shot 2022-01-20 at 1 09 28 PM" src="https://user-images.githubusercontent.com/51571627/150396751-11da6b2d-e0b4-4e62-bc71-1a8164592714.png">
