### ISSUE TITLE
Projects - Adding increased Interactivity to Gantt Chart

### ISSUE THREAD

**Issue by leoRysing** [Northeastern-Electric-Racing/PM-Dashboard-v2#624]
## Description

Add extensions to the Gantt chart for increased interactivity.

## Current Features

This ticket will build off of the base line functionality of the individual project Gantt chart. This will work as the current features.

## Desired Additional Features

Desired functionality consists of some of the following;
- [ ] The title of the work package should be a link to that work package’s page
- [x] Visually show information relating to the start date and duration for the user on hover. Start date should be present in line with the title, duration should be displayed below
- [ ] Budget should be displayed on hover, below the Duration of the work package
- [ ] Percent completion should be displayed below that

**Comment by jamescd18** [comment]
>  The title of the work package should be a link to that work package’s page

Not sure that's possible with `react-google-charts`. It uses SVG to build it and doesn't seem to have API access to configure the row titles.

> Visually show information relating to the start date and duration for the user on hover. Start date should be present in line with the title, duration should be displayed below

Roughly provided already by default.
<img width="375" alt="Screen Shot 2022-06-16 at 7 22 26 PM" src="https://user-images.githubusercontent.com/51571627/174193989-c83864a9-c890-4c76-b5f7-84c1e4c22db1.png">

> Budget should be displayed on hover, below the Duration of the work package

Budgets are not allocated by work package, so can't do this.

> Percent completion should be displayed below that

See screenshot, this is provided by default.
