### ISSUE TITLE
Projects - Forced Page Reloads Make Debugging Difficult

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#662]
### Desired Changes

Let's remove the forced page reloads because those make it all the more difficult to debug the application. Theoretically the `react-query` package should handle refreshing the data, especially if we improve the way we use it.

**Comment by anthonybernardi** [comment]
this functionality was needed to take the user out of the edit form. Now they are stuck in the edit form after pressing save which is confusing

**Comment by anthonybernardi** [comment]
Acceptance criteria: after the successful mutation is sent, the page takes the user out of the edit form and back to the view form of the project (but without forcing a refresh i guess lol)
