### ISSUE TITLE
General - Clean Up Back-End by Replacing Spread Operator with Specific Fields

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#665]
## Overview

Remove usages of the spread operator `...` and replace them with specific field definition so that only the desired fields are provided by the back-end to requesting clients.

This will improve security by avoiding leaking extra information from the back-end.

## Tickets

- [x] #666
- [x] #667
- [x] #668
- [x] #689

Example:
https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/3f6a69d3eaa925c727d1c82fbca216040b12a8db/src/backend/functions/projects.ts#L97

**Comment by Ari-S-123** [comment]
All tickets in this epic have been completed.
