### ISSUE TITLE
Change Requests - Create Dummy CR API Endpoint

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#68]
Create a dummy API endpoint similar to #67 for the `/change-requests` path. Returned data should be an array of change requests. Change requests have at bare minimum an ID, associated WBS#, submitter, and type. 

---

Here's a quick outline of potential steps for this issue.
- [x] Add file to `/backend/functions/`
- [x] Add test file to `/backend/tests/`
- [x] Copy in basic serverless endpoint handler function
- [x] Add dummy data hard-coded into the file (see #74 for example)
- [ ] Add proper interface type
- [ ] Configure the handler to supply a work package as the return
- [ ] Add basic `describe()` test suite to test file
- [ ] Add a couple `it()` test cases to test suite

Not sure if this will work properly for someone else working on the issue, but it's good to have here either way.

**Comment by jamescd18** [comment]
Here's a quick outline of potential steps for this issue.
- [ ] Add file to `/backend/functions/`
- [ ] Add test file to `/backend/tests/`
- [ ] Copy in basic serverless endpoint handler function
- [ ] Add dummy data hard-coded into the file (see #74 for example)
- [ ] Add proper interface type
- [ ] Configure the handler to supply an array of change requests as the return
- [ ] Add basic `describe()` test suite to test file
- [ ] Add a couple `it()` test cases to test suite

Not sure if this will work properly for someone else working on the issue, but it's good to have here either way.

**Comment by TheElbowTurnMaster** [comment]
I'm a little confused on some of the terms here. What exactly is a work package, and where can I learn about the organization system being used?

**Comment by jamescd18** [comment]
Check out the deployed v1, it's got a glossary of terms.
