### ISSUE TITLE
[WP Creation Form] - Errors with valid data

### ISSUE THREAD

**Issue by anthonybernardi** [Northeastern-Electric-Racing/PM-Dashboard-v2#684]
### Browser(s)

Chrome, Firefox, Safari

### Platform(s)

Desktop

### Version(s)

main, production

### Observed Behavior

work package form is giving an error with valid data

### Expected Behavior

it should work and make the work package

### Steps to Reproduce

1. fill out the work package form like above
2. press submit

### Screenshots (as needed)

![image](https://user-images.githubusercontent.com/63663597/170847427-466df335-32fa-4467-9290-95f336e9886a.png)

**Comment by jamescd18** [comment]
Unreproducible
