### ISSUE TITLE
Projects - Create the WP Details Component

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#72]
Create the view-only component for displaying work package details. This should cleanly and readably display a set of key value pairs supplied by the work package API endpoint. Refer to the design sketch v4 snippet below for inspiration and context. 

---
Here's a quick outline of steps for this issue. Check them off and / or suggest edits to them as you make progress on the issue. Existing dummy components may be useful to consult for guidance ([see here](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/src/components/project-details/project-details.tsx)).
- [x] Create the component folder in `/src/components/`
- [x] Create the test file, component file, and ccs module in the component folder
- [x] Add basic TS functional component boilerplate to component file
- [x] Add basic test suite `describe()` to test file
- [x] Add the component to the main app component (so you can see the component when starting the app in development)
- [x] Configure component props to take in the proper work package details
- [x] Display all desired component props in the tsx
- [x] Add DOM element division to begin arranging / styling data elements
- [x] Add styling to CSS module file
- [x] Attach CSS styling to proper sections / DOM elements in tsx
- [x] Get the component to an aesthetically pleasing state that resembles the design sketch snippet below
- [x] Open a PR with a screenshot of the component to get review and feedback
- [x] Iterate and make changes based on feedback
- [ ] Once approved for merging, attach a screenshot of the finished component to this issue

---
Design Sketch v4 Snippet:
<img width="768" alt="Screen Shot 2021-02-07 at 12 02 50 AM" src="https://user-images.githubusercontent.com/51571627/107140580-d40fe180-68d7-11eb-8850-791f6c3eb195.png">

**Comment by lpfahler16** [comment]
<img width="1253" alt="Screen Shot 2021-04-22 at 3 13 11 PM" src="https://user-images.githubusercontent.com/46872232/115974910-31f2b380-a52e-11eb-9369-4a22c449b15f.png">
