### ISSUE TITLE
Users - Add Teams

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#732]
### Current Features

Nothing allows groupings of projects or people together.

### Desired Additional Features

Add the construct of a team with a designated team leader and team members, allow association of projects to a team.

**Comment by anthonybernardi** [comment]
questions about the definition of this stuff:
- can a user be a part of multiple teams?
- can a user be a leader of multiple teams?
- can a project be associated with multiple teams?
- can one team be associated with multiple projects?

**Comment by jamescd18** [comment]
Consensus from NER E-Board (myself, Matt, Casey via [Slack](https://nu-electric-racing.slack.com/archives/C02U5TKHLER/p1656271451752289)):

> - can a user be a part of multiple teams?

Yes

> - can a user be a leader of multiple teams?

No

> - can a project be associated with multiple teams?

No

> - can one team be associated with multiple projects?

Yes
